




const ds=[

{
    id: 1,
    name: 'Abrillantador para Muebles',
    precio: 44,
    nombre_imagen: 'imagen1.png',
    existencia: 100,
    estado: 1
  },
{
    id: 2,
    name: 'Aceite Rojo P/Madera',
    precio: 74 ,
    nombre_imagen: 'imagen2.png',
    existencia: 100,
    estado: 1
  },
{
 
    id: 3,
    name: 'Acido Muriatico Bot 1L',
    precio: 26, 
    nombre_imagen: 'imagen3.png',
    existencia: 100,
    estado: 1
  },
{
    id : 4,
    name: 'Acido Muriatico Bot 4L',
    precio: 84, 
    nombre_imagen: 'imagen4.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 5,
    name: 'Acido Muratico Garraf 50L',
    precio: 630, 
    nombre_imagen: 'imagen5.png',
    existencia: 100,
    estado: 1,
  },
  {
    id :  6 ,
    name: 'Aromatizante',
    precio: 9 ,
    nombre_imagen: 'imagen6.png',
    existencia: 100,
    estado: 1,
  },
{
    id: 7,
    name: 'Aromatizante Perfumeria',
    precio: 16 ,
    nombre_imagen: 'imagen2.png',
    existencia: 100,
    estado: 1,
  },
  {
    id: 8,
    name: 'Cera para Pisos',
    precio: 70,
    nombre_imagen: 'imagen8.png',
    existencia: 100,
    estado: 1,
  },
{
    id: 9,
    name: 'Cera para Pisos Mantenimiento',
    precio: 38 ,
    nombre_imagen: 'imagen9.png',
    existencia: 100,
    estado: 1,
  },
  {
    id: 10,
    name: 'Soluclor 600 Pack al 6% Bidon 4L',
    precio: 24.90,
    nombre_imagen: 'imagen10.png',
    existencia: 100,
    estado: 1,
  },

  
{
    id : 13,
    name: 'Creolina',
    precio: 31.50 ,
    nombre_imagen: 'imagen13.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 14,
    name: 'Cristalizador',
    precio: 145 ,
    nombre_imagen: 'imagen14.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 15,
    name: 'Desengrasante uso Pesado',
    precio: 32 ,
    nombre_imagen: 'imagen15.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 16,
    name: 'Desengrasante uso Ligero',
    precio: 32 ,
    nombre_imagen: 'imagen16.pgn',
    existencia: 100,
    estado: 1,
  },
{
    id : 17,
    name: 'Desengrasante Citrico',
    precio: 19 ,
    nombre_imagen: 'imagen17.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 18,
    name: 'Desintegrante para Baño',
    precio: 27 ,
    nombre_imagen: 'imagen18.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 19,
    name: 'Detergente Desengrasante Clorado',
    precio: 32 ,
    nombre_imagen: 'imagen19.png',
    existencia: 100,
    estado: 1,
},
{
    id : 20,
    name: 'Detergente Liquido',
    precio: 24 ,
    nombre_imagen: 'imagen20.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 21,
    name: 'Detergente Liquido para Trastes Aroma Limon',
    precio: 16 ,
    nombre_imagen: 'imagen21.png',
    existencia: 100,
    estado: 1,
  },

{
    id : 22,
    name: 'Detergente Liquido para Trastes Aroma Limon Plus',
    precio: 35 ,
    nombre_imagen: 'imagen22.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 23,
    name: 'Elimina Olores',
    precio: 17 ,
    nombre_imagen: 'imagen23.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 24,
    name: 'Puppy Dogs',
    precio: 10 ,
    nombre_imagen: 'imagen24.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 25,
    name: 'Germiclean',
    precio: 9 ,
    nombre_imagen: 'imagen25.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 26,
    name: 'Horno Clean',
    precio: 17 ,
    nombre_imagen: 'imangen.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 27,
    name: 'Magic Clean MultiUsos Varios Aromas',
    precio: 9 ,
    nombre_imagen: 'imagen27.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 28,
    name: 'Magic Clean Tipo Fabuloso C/Repelente de Insectos',
    precio: 10 ,
    nombre_imagen: 'imagen28.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 29,
    name: 'Limpia Vidrios',
    precio: 7 ,
    nombre_imagen: 'imagen29.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 30,
    name: 'Magic Clean Tipo Fabuloso C/Amonia',
    precio: 18 ,
    nombre_imagen: 'imagen30.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 31,
    name: 'MetaBril 125 Gr',
    precio: 57 ,
    nombre_imagen: 'imagen31.png',
     existencia: 100,
    estado: 1,
  },
{
    id : 32,
    name: 'MetaBril 300 ml',
    precio: 101 ,
    nombre_imagen: 'imagen32.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 33,
    name: 'Pasta Blanca Para Pulir Pisos',
    precio: 129 ,
    nombre_imagen: 'imagen33.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 34,
    name: 'Removedro de sarro',
    precio: 44,
    nombre_imagen: 'imagen34.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 35,
    name: 'Pino Clean',
    precio: 11,
    nombre_imagen: 'imagen35.png',
     existencia: 100,
    estado: 1,
  },
{
    id : 36,
    name: 'Pino Clean Lechoso',
    precio: 9 ,
    nombre_imagen: 'imagen36.png',
     existencia: 100,
    estado: 1,
  },
{
    id : 37,
    name: 'Polvo Pulidor de Vidrios',
    precio: 13 ,
    nombre_imagen: 'imagen37.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 38,
    name: 'PolvoTierra Verde Ajax Bulto 120g Paq',
    precio: 136.50,
    nombre_imagen: 'imagen38.png',
    existencia: 100,
    estado: 1,
  },

{
    id : 41,
    name: 'Removedor de Cera',
    precio: 8.50 ,
    nombre_imagen: 'imagen41.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 42,
    name: 'Removedor de Chicle',
    precio: 52.50,
    nombre_imagen: 'imagen42.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 43,
    name: 'Repelente para Telas',
    precio: 16 ,
    nombre_imagen: 'imagen43.png',
    existencia: 100,
    estado: 1,
  },
{
    id: 44,
    name: 'Shampoo para Piso Laminado',
    precio: 16,
    nombre_imagen: 'imagen44.png',
    existencia: 100,
    estado: 1,
  },

{
    id : 47,
    name: 'Abrillantador para Llantas',
    precio: 23,
    nombre_imagen: 'imagen47.png',
    existencia: 100,
    estado: 1,
  },

{
    id : 50,
    name: 'Limpia Vidrios',
    precio: 8,
    nombre_imagen: 'imagen50.png',
    existencia: 100,
    estado: 1,
  },
{
    id: 51,
    name: 'Limpiadro en Seco P/Vestiduras',
    precio: 62,
    nombre_imagen: 'imagen51.png',
    existencia: 100,
    estado: 1,
  },
{
    id: 52,
    name: 'LubriVinil mas Brillo',
    precio: 29,
    nombre_imagen: 'imagen52.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 53,
    name: 'LubriVinil',
    precio: 25,
    nombre_imagen: 'imagen53.png',
    existencia: 100,
    estado: 1,
    
  },
{
    id: 54,
    name: 'Detergente Naranja',
    precio: 10,
    nombre_imagen: 'imagen54.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 55,
    name: 'Detergente Limon',
    precio: 10,
    nombre_imagen: 'imagen55.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 56,
    name: 'Desodorante Pino',
    precio: 7 ,
    nombre_imagen: 'imagen56.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 57,
    name: 'Desodorante Pino Fresco',
    precio: 7,
    nombre_imagen: 'imagen57.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 58,
    name: 'Desodorante Lavanda',
    precio: 7,
    nombre_imagen: 'imagen59.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 59,
    name: 'Desodorante Primavera',
    precio: 7,
    nombre_imagen: 'imagen29.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 61,
    name: 'Jabon en Polvo Espumoso',
    precio: 11,
    nombre_imagen: 'imagen61.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 62,
    name: 'Jabon en Polvo Baja Espuma',
    precio: 12,
    nombre_imagen: 'imagen62.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 63,
    name: 'Jabon Liquido',
    precio: 16,
    nombre_imagen: 'imagen63.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 64,
    name: 'Perfume P/ropa',
    precio: 19,
    nombre_imagen: 'imagen64.png',
    existencia: 100,
    estado: 1,
  },
{
    id : 65,
    name: 'Fluido Desinfectante',
    precio: 19,
    nombre_imagen: 'imagen65.png',
    existencia: 100,
    estado: 1,
  },
{
    id: 66,
    name: 'Insecticida',
    precio: 27,
    nombre_imagen: 'imagen66.png',
     existencia: 100,
    estado: 1,
  },
{
    id: 67,
    name: 'Cloro',
    precio: 6.50,
    nombre_imagen: 'imagen67.png',
     existencia: 100,
    estado: 1,
  },
{
    id : 68,
    name: 'Cloro Granulado',
    precio: 75,
    nombre_imagen: 'imagen68.png',
     existencia: 100,
    estado: 1,
  },
{
    id: 69,
    name: 'Desengrasante Para Cocina',
    precio: 28,
    nombre_imagen: 'imagen69.png',
     existencia: 100,
    estado: 1,
    
  },
{
    id : 70,
    name: 'Acondicionador Para Pisos',
    precio: 42,
    nombre_imagen: 'imagen70.png',
     existencia: 100,
    estado: 1,
  },

];

export default ds;